username = ""

diet1 = "Breakfast:\n4 boiled eggs(3 whites + 1 whole) - 140 calories\n1 slice of bread(multigrain) - 137 calories\nLunch:\n1 serving of Sheet-Pan Chicken Fajita Bowls\nwith 1/3 cooked brown rice - 450 calories\n2 scoops of whey protein with 300 ml water and\n100 ml of semi skimmed milk - 300 calories\nDinner:\n1 serving Veggie & Hummus Sandwich - 350 calories\nPre-workout snacks:\n1 banana - 105 calories\n1 apple - 95 calories \nTotal macronutrients:\n1587 calories\n187 grams of protein\n145 grams of carbohydrates\n20 grams of fats"
diet2 = "Breakfast:\n2 Poached eggs, salmon and avocado - 550 calories\nLunch:\nDouble chicken breast, broccoli and rice - 700 calories\nDinner:\nTinned tuna, quinoa, avocado and broccoli - 500 calories\nPre-workout snack:\n2 scoops of whey protein with 400 ml of water\nTotal macronutrients:\n1970 calories\n227 grams of protein\n81 grams of carbohydrates\n53 grams of fats"
diet3 = "Breakfast:\n6 egg omelette with spinach - 564 calories\n1 serving of Avocados on toast - 330 calories\nLunch:\nSalmon, sweet potatoes and sesame seeds - 700 calories\n2 scoops of whey protein with\n300 ml of whole milk - 400 calories\nDinner:\nBurger with lean beef, fries\nwhite bread roll, cup of green beans - 1450 calories\nPre-workout snack:\n1 Protein flapjack - 224 calories\nTotal Macronutrients:\n3668 calories\n247 grams of protein\n201 grams of carbohydrates\n96 grams of fats"
diet4 = "Breakfast:\nSalmon, sweet potatoes and sesame seeds - 700 calories\n2 scoops of whey protein with\n300 ml of whole milk - 400 calories\nLunch:\n250 grams chicken breast and mixed salad,\nwith 1 whole avocado - 850 calories\nDinner:\n 500 grams steak with\n220 grams baked potato - 1400 calories\n Pre-workout snack:\n 1 Protein flapjack - 224 calories\nTotal Macronutrients:\n3574 calories\n261 grams of protein\n178 grams of carbohydrates\n121 grams of fats"

dietLevel=""

diet1Text=""
diet2Text=""

diet1ID=""

diet2ID=""

SavedDiet=""

#normal 3-4 days
workout1="Day 1: Upper body\nChest: flat barbell bench press — 4 sets of 6-8 reps\nBack: bent-over barbell rows — 3 sets of 6-8 reps\nShoulders: seated dumbbell press — 3 sets of 8-10 reps\nChest/triceps: dips — 3 sets of 8-10 reps\nBack: pullups or lat pulldowns — 3 sets of 8-10 reps\nBiceps: incline dumbbell curls — 3 sets of 10-12 reps\n\nDay 2: Lower body\nLegs: barbell back squats — 4 sets of 6-8 reps\nLegs: leg press — 3 sets of 8-10 reps\nQuadriceps: seated leg extensions — 3 sets of 10-12 reps\nCalves: calf press on leg press — 4 sets of 12-15 reps\nAbs: decline crunches — 4 sets of 12-15 reps\n\nRepeat this circuit two times"
#normal 5-6 days
workout2="Day 1: Legs, shoulders, and abs\nLegs: dumbbell squats — 3 sets of 6-8 reps\nShoulders: standing shoulder press — 3 sets of 6-8 reps\nLegs: dumbbell lunge — 2 sets of 8-10 reps per leg\nShoulders: dumbbell upright rows — 2 sets of 8-10 reps\nHamstrings: Romanian dumbbell deadlift — 2 sets of 6-8 reps\nShoulders: lateral raises — 3 sets of 8-10 reps\nCalves: seated calf raises — 4 sets of 10-12 reps\nAbs: crunches with legs elevated — 3 sets of 10-12 reps\n\nDay 2: Chest and back\nChest: dumbbell bench press or floor press — 3 sets of 6-8 reps\nBack: dumbbell bent-over rows — 3 sets of 6-8 reps\nChest: dumbbell fly — 3 sets of 8-10 reps\nBack: one-arm dumbbell rows — 3 sets of 6-8 reps\nChest: pushups — 3 sets of 10-12 reps\nBack/chest: dumbbell pullovers — 3 sets of 10-12 reps\n\nDay 3: Arms and abs\nBiceps: alternating biceps curls — 3 sets of 8-10 reps per arm\nTriceps: overhead triceps extensions — 3 sets of 8-10 reps\nBiceps: seated dumbbell curls — 2 sets of 10-12 reps per arm\nTriceps: bench dips — 2 sets of 10-12 reps\nBiceps: concentration curls — 3 sets of 10-12 reps\nTriceps: dumbbell kickbacks — 3 sets of 8-10 reps per arm\nAbs: planks — 3 sets of 30-second holds\n\nRepeat this circuit once more."
#normal 2-3 days
workout3="Day 1: Legs, shoulders, and abs\nLegs: dumbbell squats — 3 sets of 6-8 reps\nShoulders: standing shoulder press — 3 sets of 6-8 reps\nLegs: dumbbell lunge — 2 sets of 8-10 reps per leg\nShoulders: dumbbell upright rows — 2 sets of 8-10 reps\nHamstrings: Romanian dumbbell deadlift — 2 sets of 6-8 reps\nShoulders: lateral raises — 3 sets of 8-10 reps\nCalves: seated calf raises — 4 sets of 10-12 reps\nAbs: crunches with legs elevated — 3 sets of 10-12 reps\n\nDay 2: Chest and back\nChest: dumbbell bench press or floor press — 3 sets of 6-8 reps\nBack: dumbbell bent-over rows — 3 sets of 6-8 reps\nChest: dumbbell fly — 3 sets of 8-10 reps\nBack: one-arm dumbbell rows — 3 sets of 6-8 reps\nChest: pushups — 3 sets of 10-12 reps\nBack/chest: dumbbell pullovers — 3 sets of 10-12 reps\n\nDay 3: Arms and abs\nBiceps: alternating biceps curls — 3 sets of 8-10 reps per arm\nTriceps: overhead triceps extensions — 3 sets of 8-10 reps\nBiceps: seated dumbbell curls — 2 sets of 10-12 reps per arm\nTriceps: bench dips — 2 sets of 10-12 reps\nBiceps: concentration curls — 3 sets of 10-12 reps\nTriceps: dumbbell kickbacks — 3 sets of 8-10 reps per arm\nAbs: planks — 3 sets of 30-second holds"
#another 2-3 days
workout4="Day 1: Legs, shoulders\nLegs: dumbbell squats — 3 sets of 6-8 reps\nShoulders: standing shoulder press — 3 sets of 6-8 reps\nLegs: dumbbell lunge — 2 sets of 8-10 reps per leg\nShoulders: dumbbell upright rows — 2 sets of 8-10 reps\nHamstrings: Romanian dumbbell deadlift — 2 sets of 6-8 reps\nShoulders: lateral raises — 3 sets of 8-10 reps\nCalves: seated calf raises — 4 sets of 10-12 reps\n\nDay 2: Chest and back\nChest: dumbbell bench press or floor press — 3 sets of 6-8 reps\nBack: dumbbell bent-over rows — 3 sets of 6-8 reps\nChest: dumbbell fly — 3 sets of 8-10 reps\nBack: one-arm dumbbell rows — 3 sets of 6-8 reps\nChest: pushups — 3 sets of 10-12 reps\nBack/chest: dumbbell pullovers — 3 sets of 10-12 reps\n\nDay 3: Arms and abs\nBiceps: alternating biceps curls — 3 sets of 8-10 reps per arm\nTriceps: overhead triceps extensions — 3 sets of 8-10 reps\nBiceps: seated dumbbell curls — 2 sets of 10-12 reps per arm\nTriceps: bench dips — 2 sets of 10-12 reps\nBiceps: concentration curls — 3 sets of 10-12 reps\nTriceps: dumbbell kickbacks — 3 sets of 8-10 reps per arm\nAbs: planks — 3 sets of 30-second holds"
#kids workout
workout5="Day 1: Full body\nLegs: barbell back squats — 3 sets of 5 reps\nChest: flat barbell bench press — 3 set of 5 reps\nBack: seated cable rows — 3 sets of 6-8 reps\nShoulders: seated dumbbell shoulder press — 3 sets of 6-8 reps\nTriceps: cable rope triceps pushdowns — 3 sets of 8-10 reps\nShoulders: lateral raises — 3 sets of 10-12 reps\nCalves: seated calf raises — 3 sets of 10-12 reps\nAbs: planks — 3 sets of 30-second holds\n\nDay 2: Full body\nBack/hamstrings: barbell or trap bar deadlifts — 3 sets of 5 reps\nBack: pullups or lat pulldowns — 3 sets of 6-8 reps\nChest: barbell or dumbbell incline press — 3 sets of 6-8 reps\nShoulders: machine shoulder press — 3 sets of 6-8 reps\nBiceps: barbell or dumbbell biceps curls — 3 sets of 8-10 reps\nShoulders: reverse machine fly — 3 sets of 10-12 reps\nCalves: standing calf raises — 3 sets of 10-12 reps\n\nDay 3: Full body\nLegs: leg press — 3 sets of 5 reps\nBack: T-bar rows — 3 sets of 6-8 reps\nChest: machine or dumbbell chest fly — 3 sets of 6-8 reps\nShoulders: one-arm dumbbell shoulder press — 3 sets of 6-8 reps\nTriceps: dumbbell or machine triceps extensions — 3 sets of 8-10 reps\nShoulders: cable or dumbbell front raises — 3 sets of 10-12 reps\nCalves: seated calf raises — 3 sets of 10-12 reps\nAbs: decline crunches — 3 sets of 10-12 reps"
#another kids
workout6="Day 1: Full body\nLegs: barbell back squats — 3 sets of 5 reps\nChest: flat barbell bench press — 3 set of 5 reps\nBack: seated cable rows — 3 sets of 6-8 reps\nShoulders: seated dumbbell shoulder press — 3 sets of 6-8 reps\nTriceps: cable rope triceps pushdowns — 3 sets of 8-10 reps\nShoulders: lateral raises — 3 sets of 10-12 reps\nCalves: seated calf raises — 3 sets of 10-12 reps\nAbs: planks — 3 sets of 30-second holds\n\nDay 2: Full body\nBack/hamstrings: barbell or trap bar deadlifts — 3 sets of 5 reps\nBack: pullups or lat pulldowns — 3 sets of 6-8 reps\nChest: barbell or dumbbell incline press — 3 sets of 6-8 reps\nShoulders: machine shoulder press — 3 sets of 6-8 reps\nBiceps: barbell or dumbbell biceps curls — 3 sets of 8-10 reps\nShoulders: reverse machine fly — 3 sets of 10-12 reps\nCalves: standing calf raises — 3 sets of 10-12 reps\n\nDay 3: 2 hours of playing any sport you like"
#another 3-4 days
workout7="Day 1: Legs, shoulders, and abs\nLegs: dumbbell squats — 3 sets of 6-8 reps\nShoulders: standing shoulder press — 3 sets of 6-8 reps\nLegs: dumbbell lunge — 2 sets of 8-10 reps per leg\nShoulders: dumbbell upright rows — 2 sets of 8-10 reps\nHamstrings: Romanian dumbbell deadlift — 2 sets of 6-8 reps\nShoulders: lateral raises — 3 sets of 8-10 reps\nCalves: seated calf raises — 4 sets of 10-12 reps\nAbs: crunches with legs elevated — 3 sets of 10-12 reps\n\nDay 2: Chest and back\nChest: dumbbell bench press or floor press — 3 sets of 6-8 reps\nBack: dumbbell bent-over rows — 3 sets of 6-8 reps\nChest: dumbbell fly — 3 sets of 8-10 reps\nBack: one-arm dumbbell rows — 3 sets of 6-8 reps\nChest: pushups — 3 sets of 10-12 reps\nBack/chest: dumbbell pullovers — 3 sets of 10-12 reps\n\nDay 3: Arms and abs\nBiceps: alternating biceps curls — 3 sets of 8-10 reps per arm\nTriceps: overhead triceps extensions — 3 sets of 8-10 reps\nBiceps: seated dumbbell curls — 2 sets of 10-12 reps per arm\nTriceps: bench dips — 2 sets of 10-12 reps\nBiceps: concentration curls — 3 sets of 10-12 reps\nTriceps: dumbbell kickbacks — 3 sets of 8-10 reps per arm\nAbs: planks — 3 sets of 30-second holds\n\nDay 4: Play any sport for 2 hours."
#another 5-6 days
workout8="Day 1: Upper body\nChest: flat barbell bench press — 4 sets of 6-8 reps\nBack: bent-over barbell rows — 3 sets of 6-8 reps\nShoulders: seated dumbbell press — 3 sets of 8-10 reps\nChest/triceps: dips — 3 sets of 8-10 reps\nBack: pullups or lat pulldowns — 3 sets of 8-10 reps\nBiceps: incline dumbbell curls — 3 sets of 10-12 reps\n\nDay 2: Lower body\nLegs: barbell back squats — 4 sets of 6-8 reps\nLegs: leg press — 3 sets of 8-10 reps\nQuadriceps: seated leg extensions — 3 sets of 10-12 reps\nCalves: calf press on leg press — 4 sets of 12-15 reps\nAbs: decline crunches — 4 sets of 12-15 reps\n\nRepeat this circuit three times"

workoutLevel=""

workout1Text=""
workout2Text=""

workout1ID=""
workout2ID=""

SavedWorkout=""

UKAvgBMI = 27.2

UKAvgBodyfat_Male = 23.2
UKAvgBodyfat_Female = 33.7

bodyfat=""
BMIscore=""